### ISSUE TITLE
update the multicore link particles function with a version not using data.table

### ISSUE THREAD

**Issue by jasongriffiths** [pennekampster/bemovi#17]
data.table class objects seem to conflict with the parallel ClusterApply loops. Providing regular data.frames to the cluster seems to work. Perhaps this is the easiest workaround and wont really influence speed.

**Comment by jasongriffiths** [comment]
Updated versions of multicore packages for check corrupt, create overlay and linkparticles is available on in the improvements branch. These do not use mcapply and are crossplatform.

the current multicore linkparticles function on the master branch needs to be removed as it is not crossplatform.

**Comment by pennekampster** [comment]
Multicore versions were tested on Windows and work fine. Will stay in the development version first, however.
