### ISSUE TITLE
add merge_data checks and alter/check video info input

### ISSUE THREAD

**Issue by jasongriffiths** [pennekampster/bemovi#18]
It is quite easy to have mismatches between the output of the trajectory/morphology data and the video input text file.

This can occur for example if file names do not match or if there are differing lengths or simply because spaces are used instead of tabs to separate text input.

Perhaps a .csv file would avoid the spacing issues and some checks could also be made to inform the user that there video input metadata is inconsistent with the names of the raw files.

**Comment by pennekampster** [comment]
I have implemented these checks now, suggesting reasons for failing merges. csv seems safer, but I do not want to change this now that the package is already getting used by some people. The hints should help troubleshoot issues with names and wrong file format.
