### ISSUE TITLE
possible problem removing file extensions from file names

### ISSUE THREAD

**Issue by opetchey** [pennekampster/bemovi#34]
In the merge_data function

I'm not sure this syntax works: sub(".cxd | .avi", "", morphology.data$file)

Also, should also remove all of video.description.file, trajectory_data, and morphology_data.

**Comment by pennekampster** [comment]
Thanks, the command was redundant and indeed probably does not work. I have removed the line. There is a working command for stripping file extensions from trajectory_data and morphology_data in the respective functions compiling the two databases.
