### ISSUE TITLE
Trouble with the link_particles function

### ISSUE THREAD

**Issue by garnier-aurelie** [pennekampster/bemovi#43]
Here is the error message. I think it concerns the merging of ijout.txt files...

Error in `[.data.table`(data, !(diff(X) == 0 & diff(Y) == 0), ) : 
  i evaluates to a logical vector length 12336 but there are 12337 rows. Recycling of logical i is no longer allowed as it hides more bugs than is worth the rare convenience. Explicitly use rep(...,length=.N) if you really need to recycle.

**Comment by pennekampster** [comment]
Fixed the problem with data.table dependency. BEMOVI should work now with newest version of data.table.

**Comment by mgree013** [comment]
I tried downloading newest version of data.table and am also running into the same error message now. Any suggestions or similar issues from others?

**Comment by pennekampster** [comment]
Hi Matthew, do you get exactly the same message? Or is it failing on that function? Maybe try re-installing bemovi again from github after installing the newest version of data.table.

**Comment by mgree013** [comment]
Yes, I was getting exactly the same error with the older version of data.table. But per your suggestion, re-installing bemovi software with new data.table worked! Love easy fixes like that. Thanks Frank

**Comment by pennekampster** [comment]
Great it works now!
