### ISSUE TITLE
trajectory summary

### ISSUE THREAD

**Issue by pennekampster** [pennekampster/bemovi#5]
We could use the median instead of the mean; probably good idea to check some of the within trajectory variation

**Comment by opetchey** [comment]
I don't understand this. Can you expand?

**Comment by pennekampster** [comment]
It's just that the mean would be more strongly affected by, say an erroneous measurement of size due to merging of an individual with a large debris particle, than the median. I am also not sure all traits we average are normally distributed.

**Comment by opetchey** [comment]
I see. Agree. Suggest we put a switch in the function, for summarise with median or mean, with median as the default.

**Comment by pennekampster** [comment]
Issue fixed by Marco.
